/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDownload: typeof import('./src/components/Footer/AppDownload.vue')['default']
    Asset: typeof import('./src/components/Header/User/Asset.vue')['default']
    Collapse: typeof import('./src/components/Footer/Collapse.vue')['default']
    Community: typeof import('./src/components/Footer/Community.vue')['default']
    ConfigProvider: typeof import('./src/components/ConfigProvider/ConfigProvider.vue')['default']
    Copyright: typeof import('./src/components/Footer/Copyright.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Index: typeof import('./src/components/Header/Action/Index.vue')['default']
    Inmail: typeof import('./src/components/Header/Action/Inmail.vue')['default']
    Language: typeof import('./src/components/Header/Action/Language.vue')['default']
    LanguageCurrency: typeof import('./src/components/Action/LanguageCurrency.vue')['default']
    ExitConfirm: typeof import('./src/components/User/ExitConfirm.vue')['default']
    Link: typeof import('./src/components/Header/Link.vue')['default']
    MenuItem: typeof import('./src/components/Header/User/MenuItem.vue')['default']
    Nav: typeof import('./src/components/Footer/Nav.vue')['default']
    Popover: typeof import('./src/components/Header/Popover.vue')['default']
    Qrcode: typeof import('./src/components/Header/Action/Qrcode.vue')['default']
    Record: typeof import('./src/components/Header/User/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/Header/Action/Theme.vue')['default']
    Unlogin: typeof import('./src/components/Header/User/Unlogin.vue')['default']
    User: typeof import('./src/components/Header/User/User.vue')['default']
  }
}
