/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDownload: typeof import('./src/components/Footer/AppDownload.vue')['default']
    Collapse: typeof import('./src/components/Footer/Collapse.vue')['default']
    Community: typeof import('./src/components/Footer/Community.vue')['default']
    ConfigProvider: typeof import('./src/components/ConfigProvider/ConfigProvider.vue')['default']
    Copyright: typeof import('./src/components/Footer/Copyright.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    LanguageCurrency: typeof import('./src/components/Action/LanguageCurrency.vue')['default']
    ExitConfirm: typeof import('./src/components/User/ExitConfirm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
